### ISSUE TITLE
Parameter conversion python to C.

### ISSUE THREAD

**Issue by faruknane** [tfedor/dzo-arap#4]
Hi, I had **"int too long to convert"** error. However **I solved it by using np.int64()**
-> `self._lib.compute_mask(np.int64(mask.data), np.int64(orig.data), width, height, tolerance)`
then I got this error `"ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1"`

In Cpp file, compute_mask function expects **bool and char arrays as the first two parameters**.
But in python code mask.data and orig.data are integer types. How do you expect it to be converted automatically from int to bool* and char* ?

I mean how does it work for you and not for me?

I changed the function in CWRAPPER.dll

```
def mask(self, mask, orig, width, height, tolerance):
                print(type(mask.data))
                print(type(orig.data))
                print(width)
                print(height)
                print(tolerance)
                self._lib.compute_mask(np.int64(mask.data), np.int64(orig.data), width, height, tolerance) #line16

```

****
Full of the error I get:

C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master>python main.py
<class 'int'>
<class 'int'>
600
500
10
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    app = Application("assets/taz.jpg")
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\Application.py", line 18, in __init__
    self.load_image(path)
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\Application.py", line 30, in load_image
    self._image = ImageHelper(self._cw, path)
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\ImageHelper.py", line 28, in __init__
    self._compute_mask()
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\ImageHelper.py", line 76, in _compute_mask
    self.cw.mask(self.cmask, self.corig, self.width, self.height, 10)
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\CWrapper.py", line 16, in mask
    self._lib.compute_mask(np.int64(mask.data), np.int64(orig.data), width, height, tolerance)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1

****
Can you explain that how you expect it to be converted from int to bool* and char* automatically?
Do I miss something? I didn't examine the project fully.

**Comment by faruknane** [comment]
I solved those errors now. by editing the cwrapper file like this:

```
import ctypes as c
import numpy as np

class CWrapper:
    """ Wrapper for C functions """

    def __init__(self):
        self._lib = c.cdll.libarap

    def mask(self, mask, orig, width, height, tolerance):
        print(mask.data)
        print(orig.data)
        print(width)
        print(height)
        print(tolerance)
        self._lib.compute_mask(mask.data_as(c.POINTER(c.c_long)), orig.data_as(c.POINTER(c.c_long)), width, height, tolerance)

    def clear(self, orig, data, width, height):
        self._lib.clear(orig.data_as(c.POINTER(c.c_char)), data.data_as(c.POINTER(c.c_char)), width, height)

    def project(self, homography, mask, orig, data, width, height, corners):

        self._lib.project(
            homography.data,
            mask.data,
            orig.data,
            data.data,
            width,
            height,
            corners.data
        )

```

I got another error now which is:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    app.run()
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\Application.py", line 40, in run
    self._run_once()
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\Application.py", line 55, in _run_once
    self._grid.project()
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\Grid.py", line 212, in project
    box.project(self._image)
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\Box.py", line 175, in project
    self._homography()
  File "C:\Users\Faruk\Downloads\dzo-arap-master\dzo-arap-master\classes\Box.py", line 167, in _homography
    h = np.linalg.solve(self.H_A, self.H_B)
  File "C:\Users\Faruk\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\linalg\linalg.py", line 394, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
TypeError: No loop matching the specified signature and casting
was found for ufunc solve1

I'm so bored with these errors. gonna cry...


```
def _homography(self):
        """
        Computes inverse homography.
        Source is initial position of the box, target is current boundary.
        """

        for i in range(0, 4):
            s = self._rigid[i]
            t = self.boundary[i]
            self.H_A[2*i][6] = -s.ix*t.x
            self.H_A[2*i][7] = -s.iy*t.x

            self.H_A[2*i+1][6] = -s.ix*t.y
            self.H_A[2*i+1][7] = -s.iy*t.y

            self.H_B[2*i] = t.x
            self.H_B[2*i+1] = t.y
        print(self.H_A)
        print(self.H_B)
        h = np.linalg.solve(self.H_A, self.H_B) #throws error line 167
        self.H = np.linalg.inv(np.array([[h[0], h[1], h[2]],
                                         [h[3], h[4], h[5]],
                                         [h[6], h[7],   1]]))

```
here are the values of H_A and H_B:

[[44 43 1 0 0 0 -1936.0 -1892.0]
 [0 0 0 44 43 1 -1892.0 -1849.0]
 [76 43 1 0 0 0 -5776.0 -3268.0]
 [0 0 0 76 43 1 -3268.0 -1849.0]
 [76 75 1 0 0 0 -5776.0 -5700.0]
 [0 0 0 76 75 1 -5700.0 -5625.0]
 [44 75 1 0 0 0 -1936.0 -3300.0]
 [0 0 0 44 75 1 -3300.0 -5625.0]]

[44.0 43.0 76.0 43.0 76.0 75.0 44.0 75.0]

**Comment by faruknane** [comment]
I solved the error by writing  `h = np.linalg.solve(self.H_A.astype('float64'), self.H_B.astype('float64'))`

and guess what? now I have another error. 👎

**Comment by faruknane** [comment]
HEY pls edit your cwrapper.py as this:


```
import ctypes as c
import numpy as np

class CWrapper:
    """ Wrapper for C functions """

    def __init__(self):
        self._lib = c.cdll.libarap

    def mask(self, mask, orig, width, height, tolerance):
        self._lib.compute_mask(mask.data_as(c.POINTER(c.c_bool)), orig.data_as(c.POINTER(c.c_byte)), width, height, tolerance)

    def clear(self, orig, data, width, height):
        self._lib.clear(orig.data_as(c.POINTER(c.c_byte)), data.data_as(c.POINTER(c.c_byte)), width, height)

    def project(self, homography, mask, orig, data, width, height, corners):
        self._lib.project(
            homography.data_as(c.POINTER(c.c_double)),
            mask.data_as(c.POINTER(c.c_bool)),
            orig.data_as(c.POINTER(c.c_byte)),
            data.data_as(c.POINTER(c.c_byte)),
            width,
            height,
            corners.data_as(c.POINTER(c.c_byte))
        )

```

**Comment by faruknane** [comment]
I get 2.5 FPS, how many frame do you get per second? @tfedor

**Comment by tfedor** [comment]
Hi, as I mentioned in the README, this was just a semestral project made 4 years ago. A lot has changed since then so I guess that's where the errors come from.

Regarding FPS, I honestly don't remember.

Feel free to fork this project and try to improve it over there, I will probably archive this repo because I have no ability nor intention to further work on this.

**Comment by faruknane** [comment]
Okay, at least thank you for replying.
